### ISSUE TITLE
function not used

### ISSUE THREAD

**Issue by xieyi4650** [wps712/BitSplit#2]
I am reading your paper and run code in this repo.  
But I found that 
https://github.com/wps712/BitSplit/blob/master/main_quant_resnet18_twostep.py#L351 is not used.
where should this function be inserted?

**Comment by peiswang** [comment]
The function of "conduct_ofwa_act" is redundant, since we have put the activation quantization codes into the "quantize" function:
https://github.com/wps712/BitSplit/blob/6fa677df80fa1d3032c9e5a45627f4dedd8e5ef2/main_quant_resnet18_twostep.py#L281

**Comment by xieyi4650** [comment]
Thank you for your reply.  I have two more questions
1 why do ofwa  before do ofwa_rr which is described in the paper. And what does `rr` mean?
2 Just to confirm, method (Error Compensated Activation Quantization) is not implemented in code?

**Comment by peiswang** [comment]
1. "ofwa" is used for weight approximation. "ofwa_rr" is used for response reconstruction. We use quantization results of weight approximation as initialization for response reconstruction.
2. Yes. I did't have enough time to deal with that part of codes.

**Comment by xieyi4650** [comment]
Hi @wps712  , for method ECAQ,  how do you deal with the situation that  all values of one channel is zero in a prev_feature. If quantize with function fwa, the q and alpha will be nan for this channel.
I set q as 0 and alpha as 1, but I do not know if this is correct. 
So could you please share the code of ECAQ?  Or just key function, piece of code

**Comment by peiswang** [comment]
Which network are use testing on? I didn't notice there exist some channels with all zero values.

The channel-wise activation quantization function:
```
def ofwa_rr_oneway_act(X, signed, act_bitwidth):
    #### Optimize beta ####
    if signed:
        max_val = (1 << (act_bitwidth - 1)) - 1
        min_val = - max_val
    else:
        max_val = (1 << act_bitwidth) - 1
        min_val = 0

    def init_quantization(x):
        beta_all = np.max(np.abs(x), axis=1) / max_val
        zero_index = (beta_all == 0)
        nonzero_index = (beta_all != 0)

        beta = beta_all[nonzero_index]
        x = x[nonzero_index]

        beta_old = beta * 1.1
        count = 0
        while(np.linalg.norm(beta-beta_old) > 1e-9):
            # print(np.linalg.norm(beta-beta_old))
            q = np.round(x / np.expand_dims(beta, 1))
            # assert(False)
            q = np.clip(q, min_val, max_val)
            beta_old = beta
            beta = np.sum(x*q, axis=1) / np.sum(q*q, axis=1)
            # print(beta)
            count += 1
            if count > 1000:
                break
        beta_all[nonzero_index] = beta
        beta_all[zero_index] = np.min(beta)
        # print(beta)
        return beta_all

    beta = init_quantization(np.transpose(X, (1,0,2,3)).reshape(X.shape[1], -1))
    return beta
```

**Comment by peiswang** [comment]
@xieyi4650 Sorry, I looked into the above code, and noticed that I have dealt with the all-zero channels,  by setting the quantization scale to the smallest scale value. I didn't check if this is the best choice. The function is as follows. 
```
def ofwa_rr_oneway_act(X, signed, act_bitwidth):
    #### Optimize beta ####
    if signed:
        max_val = (1 << (act_bitwidth - 1)) - 1
        min_val = - max_val
    else:
        max_val = (1 << act_bitwidth) - 1
        min_val = 0

    def init_quantization(x):
        beta_all = np.max(np.abs(x), axis=1) / max_val
        zero_index = (beta_all == 0)
        nonzero_index = (beta_all != 0)

        beta = beta_all[nonzero_index]
        x = x[nonzero_index]

        beta_old = beta * 1.1
        count = 0
        while(np.linalg.norm(beta-beta_old) > 1e-9):
            # print(np.linalg.norm(beta-beta_old))
            q = np.round(x / np.expand_dims(beta, 1))
            # assert(False)
            q = np.clip(q, min_val, max_val)
            beta_old = beta
            beta = np.sum(x*q, axis=1) / np.sum(q*q, axis=1)
            # print(beta)
            count += 1
            if count > 1000:
                break
        beta_all[nonzero_index] = beta
        beta_all[zero_index] = np.min(beta)
        # print(beta)
        return beta_all

    ## C, -1; each row has a scaling factor
    beta = init_quantization(np.transpose(X, (1,0,2,3)).reshape(X.shape[1], -1))
```

**Comment by xieyi4650** [comment]
@wps712  I am implementing ECAQ on resnet18 in this repo(there is only resnet model in repo),  and if you can share other models I would be really appreciate it.

Another question is  that after quantizing input feature per-channel, I get beta and quantized X i.e.  \hat{X}. then when optimize W in function
`B, alpha = ofwa_rr(X, Y, B_sav, alpha, weight_bit_width, max_epoch=100)`, here X should be  \hat{X}, is that right?
And as we need to do beta[c] * W[ :, c, :, : ] if set all zero channel as min beta, does this operation affect the accuracy?

**Comment by peiswang** [comment]
Yes, the quantization scales for all-zero channel could not affect the quantization error of activations, but could affect the following weight quantization results. Actually, without all-zero channels, merging the scales from activations to weights could still affect the weight quantization results. However, ECAQ can benefit from channel-wise activation quantization. This could be one of the reasons that ECAQ achieves lower accuracy than normal channel-wise quantization. If I remember correctly, using the min value can be a good choice. You could try other configurations, such as the max value, mean value, or 1.

**Comment by xieyi4650** [comment]
Hi @wps712 , I am not very familiar to pytorch, sorry to bother you again.    There are 3 questions, 

1. The return value B_sum of get_int_B is float,  as it divided by 2**idx for every bit.  So the the quantized W i.e. B_sum is not integer. Why the operation is divide while not multiply which is the same with paper.
2. Have you implement Bit-split and stitch to mobile net. How does this method work. My experiment results is  Acc@1 1.876 Acc@5 6.172 when A8W4.  And if I implement to depth wise conv layer, then the X, Y and W should be feed into function ofwa/ofwa_rr by channel, is that right? 
3. I am implementing method ECAQ based on this repo for several days. But I can not get correct results.  Could you please share the ECAQ code?
Look forward to your reply, thank you.

**Comment by hy-chen** [comment]
> 1. "ofwa" is used for weight approximation. "ofwa_rr" is used for response reconstruction. We use quantization results of weight approximation as initialization for response reconstruction.
> 2. Yes. I did't have enough time to deal with that part of codes.

Hi @wps712 Can I ask why is ofwa_rr used for convolution layers only? I noticed in the code, for fully connected layers, ofwa is used but ofwa_rr is skipped. Thanks!

**Comment by peiswang** [comment]
Hi @hy-chen ,
The last FC layer is quantized into 8-bit. With 8-bit quantization, 'ofwa' and 'ofwa_rr' achieve similar results. Also the FC layer has 1x1 spatial size. Thus the sampling is time-consuming. To speedup the optimization, we use 'ofwa' for the last FC layer.

**Comment by wps712** [comment]
Hi @hy-chen ,
The last FC layer is quantized into 8-bit. With 8-bit quantization, 'ofwa' and 'ofwa_rr' achieve similar results. Also the FC layer has 1x1 spatial size. Thus the sampling is time-consuming. To speedup the optimization, we use 'ofwa' for the last FC layer.

**Comment by xieyi4650** [comment]
Hi @wps712  
I still wonder have you do experience on mobilenet series model,  especially method ECAQ

**Comment by peiswang** [comment]
Hi @xieyi4650 
I haven't tried that on MobileNets. Would you please try to only quantize weights without activations. And also what if just quantize the 1x1 conv without the DW. In this way we can determine where's the problem. Thanks!

**Comment by wps712** [comment]
Hi @xieyi4650 
I haven't tried that on MobileNets. Would you please try to only quantize weights without activations. And also what if just quantize the 1x1 conv without the DW. In this way we can determine where's the problem. Thanks!
