### ISSUE TITLE
formula  rm

### ISSUE THREAD

**Issue by zjxyz** [wps712/BitSplit#3]
Hi,
As for the formula rm, hoped to provide a detailed derivation. The result of my own derivation is rm=qm(j)A(ji)-sm(i), but the paper is rm=2qm(j)A(ji)-sm(i), which lacks a double relation.

**Comment by peiswang** [comment]
I have updated the README by adding the derivation. Note that both the k-th row and the k-th column of A are related to q_k, thus there is a 2 in the derivation.
