### ISSUE TITLE
Reproduce failed.

### ISSUE THREAD

**Issue by wZuck** [wps712/BitSplit#5]
Hi, I was interested in your method, so I downloaded the source code and ran it, but I didn't get the results in README.

I used the [ResNet18 pre-trained model](https://download.pytorch.org/models/resnet18-5c106cde.pth) ([this link](https://github.com/wps712/BitSplit/blob/22c0d820aaf054a5323bfa0cb9b83c28ef4c2c69/models/resnet.py#L10))provided by PyTorch.

I've attached my training log and I'm not sure what the problem is.
[output.log](https://github.com/wps712/BitSplit/files/6968755/output.log)

**Comment by Aimeeeeeee** [comment]
Did you find the answer to this question?
